# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(default=0)),
                ('contact_name', models.CharField(max_length=10000)),
                ('contact_email', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(default=0)),
                ('contact_name', models.CharField(max_length=10000)),
                ('contact_email', models.CharField(max_length=10000)),
                ('msg_content', models.CharField(default='', max_length=10000)),
                ('sent_on', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Published')),
                ('has_been_read', models.BooleanField(default=False)),
                ('contact_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_bio', models.CharField(max_length=2000)),
                ('about_location', models.CharField(max_length=100)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture_link', models.CharField(max_length=10000)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_made', models.CharField(max_length=10000)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('likes', models.IntegerField(default=0)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='user_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
