# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_bio', models.CharField(max_length=2000)),
                ('about_location', models.CharField(max_length=100)),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
